#!/usr/bin/with-contenv bash

if [ ! -f /etc/.modules_installed ]; then 

    #install additional modules
    fwconsole ma downloadinstall restapi timeconditions ivr backup cel
    fwconsole chown
    fwconsole reload
    fwconsole restart

    #enable auto-redirecting to /admin
    rm /var/www/html/index.html

    touch /etc/.modules_installed

fi
